description: 'Feel free to text me and support me on Binance: andersoncarlosfs (151298424)'
logo: '/assets/images/5F112993-7323-4DEB-A8AA-5676BED48879.jpeg'
title: 'andersoncarlosfs'
theme: 'jekyll-theme-minimal'
